version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: monday
      time: '04:00'
    open-pull-requests-limit: 10
    commit-message:
      prefix: 'chore(deps)'
      prefix-development: 'chore(deps-dev)'
    labels:
      - dependencies
    groups:
      minor-and-patch:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
      eslint:
        patterns:
          - 'eslint*'
          - '@typescript-eslint/*'
        update-types:
          - major
      testing:
        patterns:
          - 'vitest'
          - 'vite'
        update-types:
          - major
      build-tools:
        patterns:
          - 'tsup'
          - 'typescript'
        update-types:
          - major
